stages:
  - check
  - test

check:
  stage: check
  script:
    - docker compose run --rm app ruff check .
#    - cd backend
#    - pip install black mypy ruff
#    - ruff check .
#    - mypy .
#    - black . --check
  tags:
    - sso

test:
  stage: test
  script:
    - echo "Test..."
  tags:
    - sso
