stages:
  - check
  - test

check:
  stage: check
  script:
    - ruff check .
    - mypy .
    - black . --check
  tags:
    - sso

test:
  stage: test
  script:
    - echo "Test..."
  tags:
    - sso
