stages:
  - check
  - test

check:
  stage: check
  script:
    - docker compose -f docker-compose-check.yaml down
    - docker compose -f docker-compose-check.yaml up --build
    - ruff check .
    - mypy .
    - black . --check
    - docker compose -f docker-compose-check.yaml down

test:
  stage: test
  script:
    - echo "Test..."
