stages:
  - check
  - test

before_script:
  - apk add --no-cache docker-compose  # Ставим compose
  - docker-compose --version           # Проверяем установку

check:
  stage: check
  script:
    - docker-compose up app
    - ruff check .
    - mypy .
    - black . --check
  tags:
    - sso

test:
  stage: test
  script:
    - echo "Test..."
  tags:
    - sso
