services:

  app:
    env_file:
      - $env
    build:
      dockerfile: docker/Dockerfile.test
      context: ./backend
    ports:
      - "8008:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    env_file:
      - $env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5438:5432"