"""change_user

Revision ID: f87e8844e72c
Revises: 74b58b7c34e8
Create Date: 2025-05-06 11:05:59.548323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f87e8844e72c"
down_revision: Union[str, None] = "74b58b7c34e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("services", sa.ARRAY(sa.String()), nullable=False))
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "is_verified")
    op.drop_column("user", "services")
    # ### end Alembic commands ###
